service: chat-app-backend
app: chat-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: handler.app
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  exclude:
    - node_modules/**
    - .git/**
    - .serverless/**

custom:
  webpack:
    includeModules:
      forceExclude:
        - express
        - socket.io

resources:
  Resources:
    # Define any necessary resources, such as DynamoDB tables
# Add environment variables in a separate file (not included here for security)
